sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t anuagar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anuagar/docker-react npm run test

